name: Java Unit Test CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin

      - name: Compilar projeto Java
        run: |
          mkdir -p out
          javac -d out $(find src/main -name "*.java")

      - name: Compilar testes
        run: |
          javac -d out -cp out $(find src/test -name "*.java")

      - name: Rodar testes
        run: |
          echo "Rodando testes..."
          java -cp out org.junit.platform.console.ConsoleLauncher --scan-class-path || true
